name: Petclinc frontend CI-Tests on pullrequests

on:
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!develop"
      - "!release"
  push:
    branches:
      - "master"
      - "protractor-ci"

env:
  IMAGE_NAME: spring-petclinic-angular

jobs:
  CI-Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker.test Image, that one which is used for tests
        run:  docker build --build-arg environment=dev .  --file Dockerfile.tests   -t  $IMAGE_NAME:latest
      - name: Run Docker Image as Container
        run: docker run -p 8080:8080 --detach --name petclinc-frontend-container $IMAGE_NAME:latest
      - name: Run Unit-Tests (Karma)
        run:  docker exec -w /spring-petclinic-angular/  petclinc-frontend-container  npm run test
      - name: Install protractor
        run: docker exec -w /spring-petclinic-angular/ petclinc-frontend-container npm install -g protractor
      - name: Setup Webdriver
        run: docker exec -w /spring-petclinic-angular/ petclinc-frontend-container webdriver-manager update
      - name: Start Webdriver
        run: docker exec -w /spring-petclinic-angular/ petclinc-frontend-container webdriver-manager start
      - name: Run E2E-Tests(cypress)
        run: docker exec -w /spring-petclinic-angular/ petclinc-frontend-container npm run e2e
